// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package clat

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type clatIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	clatMapClatCounters = "clat_counters"
	clatProgClatEgress  = "clat_egress"
	clatProgClatIngress = "clat_ingress"
	clatVarCLAT_PREFIX  = "CLAT_PREFIX"
	clatVarERR_IP4      = "ERR_IP4"
	clatVarPOD_IP4      = "POD_IP4"
	clatVarPOD_IP6      = "POD_IP6"
)

// loadClat returns the embedded CollectionSpec for clat.
func loadClat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ClatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load clat: %w", err)
	}

	return spec, err
}

// loadClatObjects loads clat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*clatObjects
//	*clatPrograms
//	*clatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadClatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadClat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// clatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clatSpecs struct {
	clatProgramSpecs
	clatMapSpecs
	clatVariableSpecs
}

// clatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clatProgramSpecs struct {
	ClatEgress  *ebpf.ProgramSpec `ebpf:"clat_egress"`
	ClatIngress *ebpf.ProgramSpec `ebpf:"clat_ingress"`
}

// clatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clatMapSpecs struct {
	ClatCounters *ebpf.MapSpec `ebpf:"clat_counters"`
}

// clatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type clatVariableSpecs struct {
	CLAT_PREFIX *ebpf.VariableSpec `ebpf:"CLAT_PREFIX"`
	ERR_IP4     *ebpf.VariableSpec `ebpf:"ERR_IP4"`
	POD_IP4     *ebpf.VariableSpec `ebpf:"POD_IP4"`
	POD_IP6     *ebpf.VariableSpec `ebpf:"POD_IP6"`
}

// clatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadClatObjects or ebpf.CollectionSpec.LoadAndAssign.
type clatObjects struct {
	clatPrograms
	clatMaps
	clatVariables
}

func (o *clatObjects) Close() error {
	return _ClatClose(
		&o.clatPrograms,
		&o.clatMaps,
	)
}

// clatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadClatObjects or ebpf.CollectionSpec.LoadAndAssign.
type clatMaps struct {
	ClatCounters *ebpf.Map `ebpf:"clat_counters"`
}

func (m *clatMaps) Close() error {
	return _ClatClose(
		m.ClatCounters,
	)
}

// clatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadClatObjects or ebpf.CollectionSpec.LoadAndAssign.
type clatVariables struct {
	CLAT_PREFIX *ebpf.Variable `ebpf:"CLAT_PREFIX"`
	ERR_IP4     *ebpf.Variable `ebpf:"ERR_IP4"`
	POD_IP4     *ebpf.Variable `ebpf:"POD_IP4"`
	POD_IP6     *ebpf.Variable `ebpf:"POD_IP6"`
}

// clatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadClatObjects or ebpf.CollectionSpec.LoadAndAssign.
type clatPrograms struct {
	ClatEgress  *ebpf.Program `ebpf:"clat_egress"`
	ClatIngress *ebpf.Program `ebpf:"clat_ingress"`
}

func (p *clatPrograms) Close() error {
	return _ClatClose(
		p.ClatEgress,
		p.ClatIngress,
	)
}

func _ClatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed clat_bpfel.o
var _ClatBytes []byte
